//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcesosNocturnosSAI.PackagesExecutionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://schemas.datacontract.org/2004/07/WcfPackagesExecution")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProcesosNocturnosSAI.PackagesExecutionService.Variable[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProcesosNocturnosSAI.PackagesExecutionService.DTSResponse))]
    public partial class Variable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTSResponse", Namespace="http://schemas.datacontract.org/2004/07/WcfPackagesExecution")]
    [System.SerializableAttribute()]
    public partial class DTSResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DtsErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DtsErrors {
            get {
                return this.DtsErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.DtsErrorsField, value) != true)) {
                    this.DtsErrorsField = value;
                    this.RaisePropertyChanged("DtsErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Fail {
            get {
                return this.FailField;
            }
            set {
                if ((this.FailField.Equals(value) != true)) {
                    this.FailField = value;
                    this.RaisePropertyChanged("Fail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PackagesExecutionService.IPackagesExecutionService")]
    public interface IPackagesExecutionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackagesExecutionService/ExecuteFromPackageFile", ReplyAction="http://tempuri.org/IPackagesExecutionService/ExecuteFromPackageFileResponse")]
        ProcesosNocturnosSAI.PackagesExecutionService.DTSResponse ExecuteFromPackageFile(string idApp, string packageFileName, string packageConfigFileName, ProcesosNocturnosSAI.PackagesExecutionService.Variable[] variables);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackagesExecutionService/ExecuteFromPackageFile", ReplyAction="http://tempuri.org/IPackagesExecutionService/ExecuteFromPackageFileResponse")]
        System.Threading.Tasks.Task<ProcesosNocturnosSAI.PackagesExecutionService.DTSResponse> ExecuteFromPackageFileAsync(string idApp, string packageFileName, string packageConfigFileName, ProcesosNocturnosSAI.PackagesExecutionService.Variable[] variables);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackagesExecutionService/ExecuteFromCatalog", ReplyAction="http://tempuri.org/IPackagesExecutionService/ExecuteFromCatalogResponse")]
        ProcesosNocturnosSAI.PackagesExecutionService.DTSResponse ExecuteFromCatalog(string idApp, string packageFileName, string projectName, ProcesosNocturnosSAI.PackagesExecutionService.Variable[] variables);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackagesExecutionService/ExecuteFromCatalog", ReplyAction="http://tempuri.org/IPackagesExecutionService/ExecuteFromCatalogResponse")]
        System.Threading.Tasks.Task<ProcesosNocturnosSAI.PackagesExecutionService.DTSResponse> ExecuteFromCatalogAsync(string idApp, string packageFileName, string projectName, ProcesosNocturnosSAI.PackagesExecutionService.Variable[] variables);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPackagesExecutionServiceChannel : ProcesosNocturnosSAI.PackagesExecutionService.IPackagesExecutionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PackagesExecutionServiceClient : System.ServiceModel.ClientBase<ProcesosNocturnosSAI.PackagesExecutionService.IPackagesExecutionService>, ProcesosNocturnosSAI.PackagesExecutionService.IPackagesExecutionService {
        
        public PackagesExecutionServiceClient() {
        }
        
        public PackagesExecutionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PackagesExecutionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackagesExecutionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackagesExecutionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProcesosNocturnosSAI.PackagesExecutionService.DTSResponse ExecuteFromPackageFile(string idApp, string packageFileName, string packageConfigFileName, ProcesosNocturnosSAI.PackagesExecutionService.Variable[] variables) {
            return base.Channel.ExecuteFromPackageFile(idApp, packageFileName, packageConfigFileName, variables);
        }
        
        public System.Threading.Tasks.Task<ProcesosNocturnosSAI.PackagesExecutionService.DTSResponse> ExecuteFromPackageFileAsync(string idApp, string packageFileName, string packageConfigFileName, ProcesosNocturnosSAI.PackagesExecutionService.Variable[] variables) {
            return base.Channel.ExecuteFromPackageFileAsync(idApp, packageFileName, packageConfigFileName, variables);
        }
        
        public ProcesosNocturnosSAI.PackagesExecutionService.DTSResponse ExecuteFromCatalog(string idApp, string packageFileName, string projectName, ProcesosNocturnosSAI.PackagesExecutionService.Variable[] variables) {
            return base.Channel.ExecuteFromCatalog(idApp, packageFileName, projectName, variables);
        }
        
        public System.Threading.Tasks.Task<ProcesosNocturnosSAI.PackagesExecutionService.DTSResponse> ExecuteFromCatalogAsync(string idApp, string packageFileName, string projectName, ProcesosNocturnosSAI.PackagesExecutionService.Variable[] variables) {
            return base.Channel.ExecuteFromCatalogAsync(idApp, packageFileName, projectName, variables);
        }
    }
}
